services:
  - type: web
    name: fiszki-pycharm-vue
    runtime: python
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DB_SERVICE_URL
        value: "https://db-service-v06e.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: CORS_ORIGINS
        value: "https://fiszkiadminpanelfrontend.vercel.app,http://localhost:5173"
      - key: ENVIRONMENT
        value: production
